### ISSUE TITLE
Support for Cosmos SDK v0.47

### ISSUE THREAD

**Issue by snowspike** [spellshape/cli#2]
- [ ] https://github.com/spellshape/cli/issues/3
- [ ] https://github.com/spellshape/cli/issues/11
- [ ] https://github.com/spellshape/cli/issues/12
