### ISSUE TITLE
Release v0.26.1

### ISSUE THREAD

**Issue by snowspike** [spellshape/cli#8]
With the current functionality.

- [ ] https://github.com/spellshape/cli/issues/9
- [x] https://github.com/spellshape/cli/issues/10
- [ ] https://github.com/spellshape/cli/issues/24
- [ ] https://github.com/spellshape/cli-plugin-network/issues/2
- [ ] https://github.com/spellshape/cli/issues/14
- [ ] make a GH release
